# Generated by Django 5.2.5 on 2025-09-05 16:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="action",
            index=models.Index(
                fields=["user", "-created"], name="actions_act_user_id_5d614b_idx"
            ),
        ),
    ]
