# Generated by Django 5.2.5 on 2025-09-05 16:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0002_image_total_likes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="image",
            index=models.Index(
                fields=["user", "-created"], name="images_imag_user_id_efc684_idx"
            ),
        ),
    ]
